name: Build Tests
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build Linux Rebel Editor
            os: ubuntu-latest
            artifact: linux-editor
            build-options: production=yes target=release_debug

          - name: Build Windows Rebel Editor on Linux
            os: ubuntu-latest
            artifact: windows-editor-mingw-linux
            build-options: platform=windows production=yes target=release_debug

          - name: Build Windows Rebel Editor using MSVC
            os: windows-latest
            artifact: windows-editor-msvc
            build-options: production=yes target=release_debug

          - name: Build Windows Rebel Editor using MinGW
            os: windows-latest
            artifact: windows-editor-mingw
            build-options: production=yes target=release_debug use_mingw=yes

          - name: Build macOS Rebel Editor
            os: macOS-latest
            artifact: macos-editor
            build-options: production=yes target=release_debug

          - name: Build Android Rebel Engine Library
            os: ubuntu-latest
            artifact: android-engine-library-arm64
            build-options: platform=android production=yes tools=no target=release

          - name: Build iOS Rebel Engine Library
            os: macOS-latest
            artifact: ios-engine-library-arm64
            build-options: platform=ios production=yes tools=no target=release

          - name: Build Web Rebel Engine
            os: ubuntu-latest
            artifact: web-engine
            build-options: platform=web production=yes tools=no target=release

    steps:
      - name: Checkout Rebel Build Action
        uses: actions/checkout@v4

      - name: Build Rebel
        id: build
        uses: ./
        with:
          artifact: ${{ matrix.artifact }}
          build-options: ${{ matrix.build-options }}

      - name: Check build output filename
        run: |
          #Echo build output filename:
          echo ${{ steps.build.outputs.build-filename }}
